package Banco.Formularios;

import Banco.Clases.CBanco;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmPrincipal.java
 *
 * Created on 26/04/2010, 09:31:17 PM
 */
import Banco.Clases.CCuenta;
import javax.swing.JOptionPane;

/**
 *
 * @author elKsa
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    
     CBanco b =new CBanco();
    
    
    
    /** Creates new form frmPrincipal */
    public frmPrincipal() {
        initComponents();

        this.setLocationRelativeTo(getRootPane());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiSalir = new javax.swing.JMenuItem();
        jmOpciones = new javax.swing.JMenu();
        jmiAdicionarCuenta = new javax.swing.JMenuItem();
        jmiCantClientes = new javax.swing.JMenuItem();
        jmiSaldoAcumulado = new javax.swing.JMenuItem();
        jmiCuentaMayorSaldo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banco");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36));
        jLabel1.setText("Laboratorio #9.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("Implementación de problemas aplicando");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel3.setText("los concepto de Polimorfismo e Interfaces.");

        jmArchivo.setText("Archivo");

        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiSalir);

        jMenuBar1.add(jmArchivo);

        jmOpciones.setText("Opciones");

        jmiAdicionarCuenta.setText("Adicionar Cuenta");
        jmiAdicionarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAdicionarCuentaActionPerformed(evt);
            }
        });
        jmOpciones.add(jmiAdicionarCuenta);

        jmiCantClientes.setText("Cantidad de clientes");
        jmOpciones.add(jmiCantClientes);

        jmiSaldoAcumulado.setText("Saldo acumulado");
        jmOpciones.add(jmiSaldoAcumulado);

        jmiCuentaMayorSaldo.setText("Cuenta de mayor saldo");
        jmOpciones.add(jmiCuentaMayorSaldo);

        jMenuBar1.add(jmOpciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiAdicionarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAdicionarCuentaActionPerformed
     frmAdicionarCuenta v= new frmAdicionarCuenta(this, true,b);
     v.setVisible(true);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jmiAdicionarCuentaActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenu jmOpciones;
    private javax.swing.JMenuItem jmiAdicionarCuenta;
    private javax.swing.JMenuItem jmiCantClientes;
    private javax.swing.JMenuItem jmiCuentaMayorSaldo;
    private javax.swing.JMenuItem jmiSaldoAcumulado;
    private javax.swing.JMenuItem jmiSalir;
    // End of variables declaration//GEN-END:variables

}
